name: dtmark
version: 0.6.1
author: "unknownloner"
description: Basic game library
homepage: "https://github.com/unknownloner/DTMark"
dependencies:
  browser_detect: ">=1.0.3 <2.0.0"
  vector_math: ">=1.4.3 <2.0.0"
