name: dtmark
version: 0.13.4
author: unknownloner <unknownloner.online@gmail.com>
description: Basic game library
homepage: https://github.com/unknownloner/DTMark
dependencies:
  browser_detect: '>=1.0.3 <2.0.0'
  vector_math: '>=1.4.3 <2.0.0'
  collection: '>=1.1.0 <2.0.0'
